[package]
name = "mosaic"
version = "0.1.0"
authors = ["Aram Drevekenin <aram@poor.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backtrace = "0.3.55"
bincode = "1.3.1"
futures = "0.3.5"
libc = "0.2"
nix = "0.17.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
signal-hook = "0.1.10"
strip-ansi-escapes = "0.1.0"
structopt = "0.3"
termion = { git = "https://gitlab.com/TheLostLambda/termion.git", features = ["serde"] }
termios = "0.3"
unicode-truncate = "0.1.1"
unicode-width = "0.1.8"
vte = "0.8.0"
wasmer = "1.0.0"
wasmer-wasi = "1.0.0"

[dependencies.async-std]
version = "1.3.0"
features = ["unstable"]

[dev-dependencies]
insta = "0.16.1"

[build-dependencies]
structopt = "0.3"

[profile.release]
lto = true
