[package]
name = "mosaic"
version = "0.1.0"
authors = ["Aram Drevekenin <aram@poor.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termios = "0.3"
libc = "0.2"
nix = "0.17.0"
signal-hook = "0.1.10"
unicode-width = "0.1.8"
unicode-truncate = "0.1.1"
vte = "0.8.0"
futures = "0.3.5"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.1"
structopt = "0.3"
serde_yaml = "0.8"

[dependencies.async-std]
version = "1.3.0"
features = ["unstable"]

[dev-dependencies]
insta = "0.16.1"
