[package]
name = "mosaic"
version = "0.1.0"
authors = ["Aram Drevekenin <aram@poor.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.5.2"
backtrace = "0.3.55"
bincode = "1.3.1"
futures = "0.3.5"
libc = "0.2"
nix = "0.17.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
signal-hook = "0.1.10"
structopt = "0.3"
termios = "0.3"
unicode-truncate = "0.1.1"
unicode-width = "0.1.8"
vte = "0.8.0"

[dependencies.async-std]
version = "1.3.0"
features = ["unstable"]

[dependencies.wasmer]
git = "https://github.com/wasmerio/wasmer.git"
optional = true

[dependencies.wasmer-wasi]
git = "https://github.com/wasmerio/wasmer.git"
optional = true

[features]
wasm-wip = ["wasmer", "wasmer-wasi"]

[dev-dependencies]
insta = "0.16.1"
